Add files via upload

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -239,63 +239,60 @@ phases:
           
           # CHANGE REQUEST JSON PAYLOAD
           JSON_PAYLOAD=$(cat <<EOF
-        {
-          "requested_by": "$REQUESTED_BY",
-          "assignment_group": "$ASSIGNMENT_GROUP",
-          "priority": "$PRIORITY",
-          "description": "$description",
-          "u_change_category":"$u_change_category",
-          "u_change_subcategory":"$u_change_subcategory",
-          "reason":"$reason",
-          "u_business_approval":"$u_business_approval",
-          "u_proyecto":"$u_proyecto",
-          "u_risk_on_freeze":"$u_risk_on_freeze",
-          "u_risk_non_implement":"$u_risk_non_implement",
-          "u_rfc_dev":"$u_rfc_dev",
-          "u_rfc_test":"$u_rfc_test",
-          "u_impacto_negocio":"$u_impacto_negocio",
-          "u_tiempo":"$u_tiempo",
-          "u_impact_description":"$u_impact_description",
-          "u_noimpacto":"$u_noimpacto",
-          "justification":"$justification",
-          "u_account_id":"$u_account_id",
-          "u_commit_id":"884c61416a0e144a9e3ade4be9fdcbbac49a00da",
-          "u_environment":"$u_environment",
-          "u_owner":"$u_owner"
-        }
-        EOF
+          {
+            "requested_by": "$REQUESTED_BY",
+            "assignment_group": "$ASSIGNMENT_GROUP",
+            "priority": "$PRIORITY",
+            "description": "$description",
+            "u_change_category":"$u_change_category",
+            "u_change_subcategory":"$u_change_subcategory",
+            "reason":"$reason",
+            "u_business_approval":"$u_business_approval",
+            "u_proyecto":"$u_proyecto",
+            "u_risk_on_freeze":"$u_risk_on_freeze",
+            "u_risk_non_implement":"$u_risk_non_implement",
+            "u_rfc_dev":"$u_rfc_dev",
+            "u_rfc_test":"$u_rfc_test",
+            "u_impacto_negocio":"$u_impacto_negocio",
+            "u_tiempo":"$u_tiempo",
+            "u_impact_description":"$u_impact_description",
+            "u_noimpacto":"$u_noimpacto",
+            "justification":"$justification",
+            "u_account_id":"$u_account_id",
+            "u_commit_id":"884c61416a0e144a9e3ade4be9fdcbbac49a00da",
+            "u_environment":"$u_environment",
+            "u_owner":"$u_owner"
+          }
+          EOF
           )
-          echo $JSON_PAYLOAD
+
+          RESPONSE=$(curl -s "$SN_INSTANCE_URL/api/now/table/change_request" \
+            --request POST \
+            --header "Accept:application/json" \
+            --header "Content-Type:application/json" \
+            --user "$SN_DEVOPS_USER:$SN_DEVOPS_PASSWORD" \
+            --data "$JSON_PAYLOAD")
+
+          CHANGE_ID=$(echo "$RESPONSE" | jq -r '.result.sys_id')
+
+          if [ "$CHANGE_ID" == "null" ] || [ -z "$CHANGE_ID" ]; then
+              echo "Error al crear el Change Request. Respuesta completa de ServiceNow:"
+              echo "$RESPONSE" | jq .  # Muestra la respuesta en un formato legible si es JSON
+
+              # Envía un mensaje con más información del error a SNS
+              aws sns publish --topic-arn "$SNS_TOPIC_ARN" \
+                  --subject "Error al crear el Change Request" \
+                  --message "Error al crear el Change Request en ServiceNow. Detalles de respuesta: $RESPONSE"
+              exit 1
+          fi
+          echo "Change Request creado con el ID: $CHANGE_ID"
+          aws sns publish --topic-arn "$SNS_TOPIC_ARN" \
+              --subject "SE HA CREADO EL CHANGE REQUEST CORRECTAMENTE" \
+              --message "El Change Request con el ID $CHANGE_ID ha sido creado correctamente."
+        else
+          echo "Change Request con el ID: $CHANGE_ID ya existe y se encuentra en con estado: $CHANGE_STATE"
         fi
-
-#           echo $JSON_PAYLOAD
-# #           RESPONSE=$(curl -s "$SN_INSTANCE_URL/api/now/table/change_request" \
-#             --request POST \
-#             --header "Accept:application/json" \
-#             --header "Content-Type:application/json" \
-#             --user "$SN_DEVOPS_USER:$SN_DEVOPS_PASSWORD" \
-#             --data "$JSON_PAYLOAD")
-
-#           CHANGE_ID=$(echo "$RESPONSE" | jq -r '.result.sys_id')
-
-#           if [ "$CHANGE_ID" == "null" ] || [ -z "$CHANGE_ID" ]; then
-#               echo "Error al crear el Change Request. Respuesta completa de ServiceNow:"
-#               echo "$RESPONSE" | jq .  # Muestra la respuesta en un formato legible si es JSON
-
-#               # Envía un mensaje con más información del error a SNS
-#               aws sns publish --topic-arn "$SNS_TOPIC_ARN" \
-#                   --subject "Error al crear el Change Request" \
-#                   --message "Error al crear el Change Request en ServiceNow. Detalles de respuesta: $RESPONSE"
-#               exit 1
-#           fi
-#           echo "Change Request creado con el ID: $CHANGE_ID"
-#           aws sns publish --topic-arn "$SNS_TOPIC_ARN" \
-#               --subject "SE HA CREADO EL CHANGE REQUEST CORRECTAMENTE" \
-#               --message "El Change Request con el ID $CHANGE_ID ha sido creado correctamente."
-#         else
-#           echo "Change Request con el ID: $CHANGE_ID ya existe y se encuentra en con estado: $CHANGE_STATE"
-#         fi
-#       - echo "El valor de CHANGE_ID es:$CHANGE_ID"
+      - echo "El valor de CHANGE_ID es:$CHANGE_ID"
 # ############################################################
 #       - echo "Monitoreando el estado del Change Request"
 #       - |
